### ISSUE TITLE
Ordering of TRISTAN IPs

### ISSUE THREAD

**Issue by cvvletter** [openhwgroup/tristan-unified-access-page#18]
We should probably order the list of TRISTAN IPs (probably by increasing WI number), because there are 62 total WIs in WP2 and WP3 alone.

**Comment by davideschiavone** [comment]
Thanks, actually the plan is to divide them by IP type, CORE, PERIPHERALS, SW, TOOLs - but also WI would be nice too, I will ask it in the mailing list

**Comment by cvvletter** [comment]
Sounds like a good plan to me. Thank you for the response!

**Comment by davideschiavone** [comment]
this is done now thanks
